在Windows平台使用多线程进行文件复制
TISUnion/QuickBackupM pull request #51
Opened 2023-07-22 12:15 UTC by tanhHeng

## 多线程在Windows平台
普通的copytree等复制函数在Windows平台上调度性能较差，无法充分利用硬盘。
使用多线程可将速度提升约**300%-600%**

## 添加内容

### 函数
通过使用`shutil.copytree`函数先获取文件列表，`threading`模块建立线程，将待复制的文件按照线程数切分成n份分配给各个线程，开始计算
极大的提高了Windows平台上的备份速度

### Config
#### copy_thread_active

默认值: `4`

建立多个线程同时请求硬盘以加快复制速度，该选项控制了建立的线程数量

当该选项设定为0时，关闭多线程复制而采用传统复制方式

## 测试
**环境：**
- Windows11 专业工作站版
- CPU i9 13900k
- 硬盘 tipro7000 RAID10 阵列（Windows RAID0存储池+镜像盘）
- 存档大小：21.3GB
- 文件数量：20,321

## 结果：
- 无多线程：**72.9**秒（60-80秒）
- 8线程：**14**秒（13-20秒）

速度提升了约**300%-600%**

2023-07-25 13:40 UTC, Fallen-Breath commented on README.md
> +### copy_thread_active
请同步维护英文文档

2023-07-25 13:41 UTC, Fallen-Breath commented on README.md
> +- 一般情况下，多线程复制能够将速度提升4-5倍(测试结果)
如果想要展示性能差异，请带上具体的测试场景

2023-07-25 13:41 UTC, Fallen-Breath commented on README.md
> +- 线程数不建议超过8
请提供建议参考来源

2023-07-25 13:42 UTC, Fallen-Breath commented on mcdreforged.plugin.json
> +	"version": "1.10.0-beta",
请不要修改版本号，这不是这一类新增功能 PR 该做的

2023-07-25 13:42 UTC, Fallen-Breath commented on mcdreforged.plugin.json
> +		"Fallen_Breath",
你只是贡献者而已，并非维护者/作者

2023-07-25 13:42 UTC, Fallen-Breath commented on quick_backup_multi/__init__.py
> +# 多线程复制文件
请使用英文来写注释，并且不要写这种翻译变量名这一类无意义的注释

2023-07-25 13:43 UTC, Fallen-Breath commented on quick_backup_multi/__init__.py
> +        for thread in range(thread_counts): # 多线程复制
考虑使用线程池 `ThreadPoolExecutor`

2023-07-25 13:44 UTC, Fallen-Breath commented on quick_backup_multi/__init__.py
> +        server_inst.logger.info(time.time()-s_time)
如果耗时展示仅用于调试，请删去

2023-07-25 13:45 UTC, Fallen-Breath commented on quick_backup_multi/__init__.py
> +            except PermissionError:
请不要无原因地抑制异常发生

2023-07-25 13:45 UTC, Fallen-Breath commented on quick_backup_multi/__init__.py
> +        if id != None:
如果耗时展示仅用于调试，请删去

2023-07-25 13:47 UTC, Fallen-Breath commented on quick_backup_multi/__init__.py
> +						server_inst.logger.warn(f"多线程复制出错，使用常规复制 {e}")
1. 请使用英文
2. 请阐述进行重试操作的原因，什么时候会出现多线程失败而单线程能成功的情况
3. 如果出现问题，请做出恰当的恢复操作，而非直接调用常规复制方法重试

2023-07-25 13:51 UTC, Fallen-Breath commented on quick_backup_multi/__init__.py
> +class MultithreadedCopy:
考虑到该类的使用方式

https://github.com/TISUnion/QuickBackupM/blob/eb06543c8dcdd583445972625aea6558f222cb82/quick_backup_multi/__init__.py#L172-L174

请不用把类当函数来用，定义一个普通的函数即可。这些成员函数都可以在函数里面定义函数

2023-07-25 13:58 UTC, Fallen-Breath commented on quick_backup_multi/__init__.py
> +						MultithreadedCopy(src_path, dst_path, config.copy_thread_active)
请正确支持 `config.is_file_ignored`

2023-07-25 13:59 UTC, Fallen-Breath requested changes
见 Files changed 页面的 review 项

2023-07-25 16:00 UTC, Fallen-Breath commented
使用线程池，支持 `enable_copy_file_range` 选项，并暴露拷贝过程中出现的问题的参考实现：

```python3
def copy_tree_fast(src_path: str, dst_path: str, ignore=None, copy_function: Callable[[str, str], object] = shutil.copy2):
	with ThreadPoolExecutor(max_workers=max(1, config.copy_thread_active), thread_name_prefix='QBMFileCopier') as pool:
		def threaded_copy(s: str, d: str):
			tasks.append((s, d, pool.submit(copy_function, s, d)))

		tasks = []
		shutil.copytree(src_path, dst_path, ignore=ignore, copy_function=threaded_copy)

	# expose the possible exceptions
	for src, dst, future in tasks:
		try:
			future.result()
		except Exception:
			server_inst.logger.error('Failed to copy file from {} to {}'.format(src, dst))
			raise	
```

```diff
@@ -130,7 +148,7 @@
 
 			server_inst.logger.info('copying {} -> {}'.format(src_path, dst_path))
 			if os.path.isdir(src_path):
-				shutil.copytree(src_path, dst_path, ignore=lambda path, files: set(filter(config.is_file_ignored, files)), copy_function=copy_file_fast)
+				copy_tree_fast(src_path, dst_path, ignore=lambda path, files: set(filter(config.is_file_ignored, files)), copy_function=copy_file_fast)
 			elif os.path.isfile(src_path):
 				dst_dir = os.path.dirname(dst_path)
 				if not os.path.isdir(dst_dir):
```

2023-07-25 16:00 UTC, Fallen-Breath commented on quick_backup_multi/config.py
> +	copy_thread_active: int = 4
请使用 `0` 或 `1` 作为默认值，让多线程复制默认关闭。毕竟该功能并非是无副作用的

2023-07-26 20:45 UTC, fattoolman commented
這邊發現到一個現象
同盤備份（980PRO）可能耗時60秒
假如是異盤備份
開服盤(980PRO) to 備份盤（KC3000 1TB）
可以減少至12秒
我的地圖大小是16G
-
CPU R5 7600X
RAM 32G 4800 dual.ch
OSDISK 980PRO 1TB
BAKDISK KC3000 1TB
OS Windows 11 Pro

2023-07-27 10:45 UTC, tanhHeng commented on README.md
> +- 一般情况下，多线程复制能够将速度提升4-5倍(测试结果)
测试部分写在了pr里
并且由于存档大小和系统环境等差异，在不同使用场景下提升差异可能较大，提升较小的可能只有20%左右

2023-07-27 10:48 UTC, tanhHeng commented on quick_backup_multi/__init__.py
> +            except PermissionError:
这里是由于session.lock在部分情况下可能会被mc锁定无法复制，从而引发permission异常。如果尝试在except中再验证一次复制的文件名，非session.lock文件则抛出异常应该能更好解决？

2023-07-27 10:50 UTC, tanhHeng commented on quick_backup_multi/__init__.py
> +						server_inst.logger.warn(f"多线程复制出错，使用常规复制 {e}")
目前的调试过程中似乎暂未发现多线程失败的情况？

2023-07-27 10:52 UTC, tanhHeng commented on quick_backup_multi/__init__.py
> +        for thread in range(thread_counts): # 多线程复制
目前仍在尝试各种不同的线程调用方式，感谢提醒，我会尝试测试线程池的调用及耗时

2023-07-27 11:30 UTC, Fallen-Breath commented on quick_backup_multi/__init__.py
> +            except PermissionError:
`session.lock` 这一类文件已可使用 [ignored_files](https://github.com/TISUnion/QuickBackupM#ignored_files) 配置进行忽略

2023-07-27 11:31 UTC, Fallen-Breath commented on README.md
> +- 一般情况下，多线程复制能够将速度提升4-5倍(测试结果)
PR 不是文档。readme 里要么不写，要么写完善

2023-07-27 14:15 UTC, Fallen-Breath commented
已于 f39a393a1afa48e5de3606ca6d8826519dd471e2 中实现并行复制

2023-07-27 14:15 UTC, closed without merging